### ISSUE TITLE
NoSQL meta-backend

### ISSUE THREAD

**Issue by dennwc** [cayleygraph/cayley#652]
We are working on generic NoSQL backend that will be used for all future document database backends.

This allows us to code all write/query optimizations in one place and automatically use them for all NoSQL backends as well as simplifying effort of supporting new databases.

Current work covers:
- [x] MongoDB
- [x] ElasticSearch #653 (strictly typed indexes and fields)
- [ ] DynamoDB #654 (hybrid, hash-based PKs)
- [ ] CouchDB/PouchDB #655 (loosely typed)
